In [3]:

import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
np.arange(10,20,2)


array([10, 12, 14, 16, 18])

In [6]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.linspace(1,2,5)


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
np.linspace(1,5,10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [9]:
np.array(np.random.randn(5),dtype='int')


array([0, 2, 0, 0, 0])

In [10]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [11]:
np.ones(2)


array([1., 1.])

In [12]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
import numpy as np
a=np.array([1,2,3,4,5],float)
a.dtype

dtype('float64')

In [14]:
a.ndim

1

In [15]:
a.shape

(5,)

In [16]:
a.itemsize

8

In [17]:
2 in a

True

In [18]:
7 in a

False

In [20]:
a=np.array(range(10),float)

In [21]:
a.ndim

1

In [24]:
a=a.reshape(2,5)
a

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [28]:
b=np.array([[2,3],[4,5]])
b

array([[2, 3],
       [4, 5]])

In [30]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
b=np.array([[2,3,3],[4,5,21],[3,4,5]])
b

array([[ 2,  3,  3],
       [ 4,  5, 21],
       [ 3,  4,  5]])

In [33]:
a=np.random.randn(24).reshape(2,3,4)
a

array([[[-0.98335915,  0.5556879 ,  0.13848415, -1.75967479],
        [-1.01870509,  0.44296139, -0.50158909, -1.13800335],
        [ 0.07438507,  1.56970446, -0.17610242, -0.86379099]],

       [[-0.97090472,  0.8640142 , -2.24659341,  0.50037046],
        [ 0.64681038,  0.39392846,  0.91650822, -1.50835268],
        [-1.28795469, -1.71734323,  0.16495938,  0.31271198]]])

In [34]:
a[0][0]

array([-0.98335915,  0.5556879 ,  0.13848415, -1.75967479])

In [35]:
a[0][1]

array([-1.01870509,  0.44296139, -0.50158909, -1.13800335])

In [37]:
import numpy as np

In [39]:
np.array([[2,3],[3,4]])

array([[2, 3],
       [3, 4]])

In [41]:
a=np.arange(10,20).reshape(5,2)
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [43]:
a[:-2]

array([[10, 11],
       [12, 13],
       [14, 15]])

In [46]:
a[2][1]

15

In [47]:
a[0:]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [49]:
a[2:]

array([[14, 15],
       [16, 17],
       [18, 19]])

In [52]:
a[0:4:1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [54]:
a[1:-2]

array([[12, 13],
       [14, 15]])

In [56]:
a=np.array([1,1,2,2,2,2,2,3,3,4,4,5,6,7,8,9])
a

array([1, 1, 2, 2, 2, 2, 2, 3, 3, 4, 4, 5, 6, 7, 8, 9])

In [57]:
a.shape

(16,)

In [58]:
print("mean=>",np.mean(a))
print("median=>",np.median(a))


mean=> 3.8125
median=> 3.0


In [59]:
print("square root",np.sqrt(a))

square root [1.         1.         1.41421356 1.41421356 1.41421356 1.41421356
 1.41421356 1.73205081 1.73205081 2.         2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [60]:
a=np.array([1,2,3],float)
a

array([1., 2., 3.])

In [61]:
b=a

In [80]:
b[0]=1000

In [81]:
b

array([1000.,    2.,    3.])

In [82]:
a[0]=100

In [83]:
a

array([100.,   2.,   3.])

In [84]:
c=a.copy()
c

array([100.,   2.,   3.])

In [85]:
print(a)
print(b)
print(c)

[100.   2.   3.]
[100.   2.   3.]
[100.   2.   3.]


In [87]:
a1=np.array([1,2,3],float)
a1

array([1., 2., 3.])

In [89]:
a1.tolist()
print(a1)
list(a1)

[1. 2. 3.]


[1.0, 2.0, 3.0]

In [90]:
type(list(a1))

list

In [91]:
a1=np.array([1,2,3],float)
s=a1.tostring()
s

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1356\3020653748.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s=a1.tostring()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [92]:
np.fromstring(s)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1356\4042211205.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([1., 2., 3.])

In [100]:
#fill
a1=np.array([1,2,3],float)
print(a1)
a1.fill(0)
print(a1)

[1. 2. 3.]
[0. 0. 0.]


In [101]:
a1=np.array([[1,2,3],[4,5,6]],float)
a1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [102]:
a1.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [104]:
a1.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [106]:
a1.flatten()

array([1., 2., 3., 4., 5., 6.])

In [110]:
x=np.array([[1,2],[3,4]],float)
y=np.array([[5,6],[7,8]],float)
np.concatenate((x,y),axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [114]:
np.concatenate((x,y),axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [120]:
#in list we cant do vectorization 
l1=[1,2,3,4,5]
l1*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [118]:
#np vectorization
s=np.array([[1,2,3],[4,5,6]],float)
s

array([[1., 2., 3.],
       [4., 5., 6.]])

In [119]:
s*2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [121]:
s1=np.array([[7,8,9],[5,2,1]],float)
s1


array([[7., 8., 9.],
       [5., 2., 1.]])

In [122]:
s+s1

array([[ 8., 10., 12.],
       [ 9.,  7.,  7.]])

In [123]:
s-s1

array([[-6., -6., -6.],
       [-1.,  3.,  5.]])

In [124]:
s*s1

array([[ 7., 16., 27.],
       [20., 10.,  6.]])